spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://127.0.0.1:3306/shopdb?useUnicode=yes&characterEncoding=UTF-8'
    username: 'root'
    password: '!QAZ3edc'
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true